#!/usr/bin/env sh
## Rebar3 3.22.1+build.5336.ref8207d824
REBAR3_VSN=${REBAR3_VSN:-3.22.1+build.5336.ref8207d824}
erl -pz /home/nick/.cache/rebar3/vsns/${REBAR3_VSN}/lib/*/ebin +sbtu +A1 -noshell -boot start_clean -s rebar3 main $REBAR3_ERL_ARGS -extra "$@"
